### ISSUE TITLE
使用bilinear初始化反卷积权重部分，为什么反卷积的卷积核大小是64*64*1*1

### ISSUE THREAD

**Issue by vissac** [wshwbluebird/LapSRN#1]
rt，感觉上采两倍，反卷积卷积核应该是4*4*1*1就可以了啊？这里不是很能理解

**Comment by Hirico** [comment]
目前代码里初始化权重方法的第一个参数接受值是 conv_ft，应该就是4，大小是 4 * 4 * 1 * 1，看起来好像没有问题

**Comment by vissac** [comment]
> 目前代码里初始化权重方法的第一个参数接受值是 conv_ft，应该就是4，大小是 4 * 4 * 1 * 1，看起来好像没有问题

昨晚神志不清看差了一行==   我的锅  谢谢了
